<?php
/*
** Archive
** Will list child categories of 'primary' category as H3s followed by all the post titles as LIs alphabetically.
**
*** Code does not work at present.
*** Options:
*** 	* Hand code separate loops for child categories as introduced to site.
***		* Keep looking for a better method of having the whole page generated by WordPress.
***
*** Not a priority at present as this feature isn't key to the site.
*/


get_header();

$top_category = $_GET['cat'];

$child_categories = get_categories( 'child_of=' . $top_category );

print_r( $child_categories);

foreach( $child_categories as $child_category ) {

	$child_category_content = new WP_Query( 'category_name=' . $child_category['category_nicename'] );
	
	if( $child_category_content->have_posts()) {
		
		echo '<h4>' . $child_category . '</h4>';
		?>
		
		<ul>
			<?php while ( $child_category_content->have_posts()) : $child_category_content->the_post(); ?>
				<li><a href="<?php the_permalink(); ?>" rel="bookmark" title="Permanent Link to <?php the_title(); ?>"><?php the_title(); ?></a></li>
			<?php endwhile; ?>
		</ul>
		<?php
	}
}

include (TEMPLATEPATH . '/main_navigation.php');

get_footer();
?>